
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomFontsWebServiceHttpPost", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandomFontsWebServiceHttpPost {


    /**
     * <br /><h3>获得随机中文简体字Web Services</h3><p>输入参数：byFontsLength = 输出中文字的数量（Integer）；返回数据：一个一维字符串数组 String()，内容为随机中文简体字。这里支持最多不超过8个中文简体字输出，如需要更多输出请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>。
     * 
     * @param byFontsLength
     * @return
     *     returns mypackage.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getChineseFonts(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "byFontsLength")
        String byFontsLength);

    /**
     * <br /><h3>获得随机英文、数字Web Services</h3><p>输入参数：byFontsLength = 输出字的数量（Integer）；返回数据：一个一维字符串数组 String()，内容为随机英文、数字。为了避免混淆只输出，只随机产生 1,2,3,4,5,6,7,8,9,A,C,D,E,F,H,K,L,M,N,P,R,S,T,W,X,Y,Z，这里支持最多不超过10个输出，如需要更多输出请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>。
     * 
     * @param byFontsLength
     * @return
     *     returns mypackage.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getCharFonts(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "byFontsLength")
        String byFontsLength);

}
