
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>随机英文、数字和中文简体字 WEB 服务</strong> 可用于验证码[<a href="http://www.webxml.com.cn/ValidateCode/ChineseValidateCode.aspx" target="_blank">演示1</a>] [<a href="http://www.webxml.com.cn/ValidateCode/EnglishValidateCode.aspx" target="_blank">演示2</a>]及其他方面，这里支持最多不超过8个随机中文简体字，10个随机英文、数字输出（一般也够了:P），如需要更多输出请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandomFontsWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/RandomFontsWebService.asmx?wsdl")
public class RandomFontsWebService
    extends Service
{

    private final static URL RANDOMFONTSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDOMFONTSWEBSERVICE_EXCEPTION;
    private final static QName RANDOMFONTSWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "RandomFontsWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webxml.com.cn/WebServices/RandomFontsWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDOMFONTSWEBSERVICE_WSDL_LOCATION = url;
        RANDOMFONTSWEBSERVICE_EXCEPTION = e;
    }

    public RandomFontsWebService() {
        super(__getWsdlLocation(), RANDOMFONTSWEBSERVICE_QNAME);
    }

    public RandomFontsWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDOMFONTSWEBSERVICE_QNAME, features);
    }

    public RandomFontsWebService(URL wsdlLocation) {
        super(wsdlLocation, RANDOMFONTSWEBSERVICE_QNAME);
    }

    public RandomFontsWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDOMFONTSWEBSERVICE_QNAME, features);
    }

    public RandomFontsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomFontsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandomFontsWebServiceSoap
     */
    @WebEndpoint(name = "RandomFontsWebServiceSoap")
    public RandomFontsWebServiceSoap getRandomFontsWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceSoap"), RandomFontsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomFontsWebServiceSoap
     */
    @WebEndpoint(name = "RandomFontsWebServiceSoap")
    public RandomFontsWebServiceSoap getRandomFontsWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceSoap"), RandomFontsWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns RandomFontsWebServiceSoap
     */
    @WebEndpoint(name = "RandomFontsWebServiceSoap12")
    public RandomFontsWebServiceSoap getRandomFontsWebServiceSoap12() {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceSoap12"), RandomFontsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomFontsWebServiceSoap
     */
    @WebEndpoint(name = "RandomFontsWebServiceSoap12")
    public RandomFontsWebServiceSoap getRandomFontsWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceSoap12"), RandomFontsWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns RandomFontsWebServiceHttpGet
     */
    @WebEndpoint(name = "RandomFontsWebServiceHttpGet")
    public RandomFontsWebServiceHttpGet getRandomFontsWebServiceHttpGet() {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceHttpGet"), RandomFontsWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomFontsWebServiceHttpGet
     */
    @WebEndpoint(name = "RandomFontsWebServiceHttpGet")
    public RandomFontsWebServiceHttpGet getRandomFontsWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceHttpGet"), RandomFontsWebServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns RandomFontsWebServiceHttpPost
     */
    @WebEndpoint(name = "RandomFontsWebServiceHttpPost")
    public RandomFontsWebServiceHttpPost getRandomFontsWebServiceHttpPost() {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceHttpPost"), RandomFontsWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomFontsWebServiceHttpPost
     */
    @WebEndpoint(name = "RandomFontsWebServiceHttpPost")
    public RandomFontsWebServiceHttpPost getRandomFontsWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "RandomFontsWebServiceHttpPost"), RandomFontsWebServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDOMFONTSWEBSERVICE_EXCEPTION!= null) {
            throw RANDOMFONTSWEBSERVICE_EXCEPTION;
        }
        return RANDOMFONTSWEBSERVICE_WSDL_LOCATION;
    }

}
